/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "Connection Identifier": {                        "en": "Connection Identifier",                            "de": "Verbindungskennung",                               "ru": "Идентификатор соединения",                         "pt": "Identificador de Conexão",                         "nl": "Verbindings-ID",                                   "fr": "Identifiant de connexion",                         "it": "Identificatore di connessione",                    "es": "Identificador de conexión",                        "pl": "Identyfikator połączenia",                         "uk": "Ідентифікатор підключення",                        "zh-cn": "连接标识符"},
    "Serial Port Id for SUP2 access. Format: /dev/tty.usbserial or COM8": {"en": "Serial Port Id for SUP2 access. Format: /dev/tty.usbserial or COM8", "de": "Serial Port ID für SUP2-Zugriff. Format: /dev/tty.usbserial oder COM8", "ru": "Идентификатор последовательного порта для доступа к SUP2. Формат: /dev/tty.usbserial или COM8.", "pt": "ID da porta serial para acesso SUP2. Formato: /dev/tty.usbserial ou COM8", "nl": "Seriële poort-id voor SUP2-toegang. Formaat: /dev/tty.usbserial of COM8", "fr": "ID de port série pour l'accès SUP2. Format : /dev/tty.usbserial ou COM8", "it": "ID porta seriale per accesso SUP2. Formato: /dev/tty.usbserial o COM8", "es": "ID de puerto serie para acceso SUP2. Formato: /dev/tty.usbserial o COM8", "pl": "Identyfikator portu szeregowego dla dostępu SUP2. Format: /dev/tty.usbserial lub COM8", "uk": "Ідентифікатор послідовного порту для доступу до SUP2. Формат: /dev/tty.usbserial або COM8", "zh-cn": "SUP2 访问的串行端口 ID。格式：/dev/tty.usbserial 或 COM8"},
};